#############################################################################
# Makefile for building: ../../../Bin/RedHatEnterpriseServer6.3_64_Release/IBDataTransfer
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? 10? 15 15:35:45 2015
# Project:  IBDataTransfer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile IBDataTransfer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_LARGEFILE_SUPPORT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -D_DYR_NEW_DEFINE_ -DNDEBUG -D_LINUX_VER -DLINUX64 -DUSING_QT -DUSE_PRIVATE_VA_DEFINITION -D_LINUX_APPARITOR_TSTRING_ -O2 -g -Wall -fmessage-length=0 -Wno-unknown-pragmas -Wno-format -fPIC -Wl,-rpath, ./ -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Ibuild -I../../Include -Ibuild
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -libverbs -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = RDMAOperation.cpp \
		RDMAParser.cpp \
		RDMAResource.cpp \
		RDMASock.cpp \
		RDMAThread.cpp \
		TimeCount.cpp \
		MsgQueue.cpp \
		DirectoryUtil.cpp \
		main.cpp 
OBJECTS       = build/RDMAOperation.o \
		build/RDMAParser.o \
		build/RDMAResource.o \
		build/RDMASock.o \
		build/RDMAThread.o \
		build/TimeCount.o \
		build/MsgQueue.o \
		build/DirectoryUtil.o \
		build/main.o
DIST          = /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		IBDataTransfer.pro
QMAKE_TARGET  = IBDataTransfer
DESTDIR       = ../../../Bin/RedHatEnterpriseServer6.3_64_Release/
TARGET        = ../../../Bin/RedHatEnterpriseServer6.3_64_Release/IBDataTransfer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../../../Bin/RedHatEnterpriseServer6.3_64_Release/ || $(MKDIR) ../../../Bin/RedHatEnterpriseServer6.3_64_Release/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IBDataTransfer.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile IBDataTransfer.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile IBDataTransfer.pro

dist: 
	@$(CHK_DIR_EXISTS) build/IBDataTransfer1.0.0 || $(MKDIR) build/IBDataTransfer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/IBDataTransfer1.0.0/ && $(COPY_FILE) --parents rdma_mt.h rdma_utils.h RDMAOperation.h RDMAParser.h RDMAResource.h RDMASock.h RDMAThread.h TimeCount.h MsgQueue.h DirectoryUtil.h build/IBDataTransfer1.0.0/ && $(COPY_FILE) --parents RDMAOperation.cpp RDMAParser.cpp RDMAResource.cpp RDMASock.cpp RDMAThread.cpp TimeCount.cpp MsgQueue.cpp DirectoryUtil.cpp main.cpp build/IBDataTransfer1.0.0/ && (cd `dirname build/IBDataTransfer1.0.0` && $(TAR) IBDataTransfer1.0.0.tar IBDataTransfer1.0.0 && $(COMPRESS) IBDataTransfer1.0.0.tar) && $(MOVE) `dirname build/IBDataTransfer1.0.0`/IBDataTransfer1.0.0.tar.gz . && $(DEL_FILE) -r build/IBDataTransfer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/RDMAOperation.o: RDMAOperation.cpp RDMAOperation.h \
		rdma_mt.h \
		rdma_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RDMAOperation.o RDMAOperation.cpp

build/RDMAParser.o: RDMAParser.cpp RDMAParser.h \
		rdma_mt.h \
		rdma_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RDMAParser.o RDMAParser.cpp

build/RDMAResource.o: RDMAResource.cpp RDMAResource.h \
		rdma_mt.h \
		rdma_utils.h \
		RDMAThread.h \
		IBDT_ErrorDefine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RDMAResource.o RDMAResource.cpp

build/RDMASock.o: RDMASock.cpp RDMASock.h \
		rdma_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RDMASock.o RDMASock.cpp

build/RDMAThread.o: RDMAThread.cpp RDMAThread.h \
		rdma_mt.h \
		rdma_utils.h \
		RDMAResource.h \
		RDMAOperation.h \
		RDMASock.h \
		TimeCount.h \
		MsgQueue.h \
		DirectoryUtil.h \
		IBDT_ErrorDefine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/RDMAThread.o RDMAThread.cpp

build/TimeCount.o: TimeCount.cpp TimeCount.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/TimeCount.o TimeCount.cpp

build/MsgQueue.o: MsgQueue.cpp MsgQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MsgQueue.o MsgQueue.cpp

build/DirectoryUtil.o: DirectoryUtil.cpp DirectoryUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/DirectoryUtil.o DirectoryUtil.cpp

build/main.o: main.cpp IBDT_ErrorDefine.h \
		rdma_mt.h \
		rdma_utils.h \
		RDMAParser.h \
		RDMAResource.h \
		RDMAThread.h \
		RDMASock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

